### ISSUE TITLE
Ini Kenapa Bang Jagoan??

### ISSUE THREAD

**Issue by Limsatrya** [MhankBarBar/whatsapp-bot#157]
ini napa ya bang?
![Screenshot (292)](https://user-images.githubusercontent.com/71541550/102005727-ba29a680-3d4d-11eb-8259-76f4014ec934.png)

**Comment by Limsatrya** [comment]
C:\Users\Asus>cd C:\

C:\>cd whatsapp-bot-main
The system cannot find the path specified.

C:\>cd whatsapp-bot-master

C:\whatsapp-bot-master>npm install gify-cli -g
C:\Users\Asus\AppData\Roaming\npm\gify -> C:\Users\Asus\AppData\Roaming\npm\node_modules\gify-cli\cli.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules\gify-cli\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules\gify-cli\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules\gify-cli\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules\gify-cli\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules\gify-cli\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.4 (node_modules\gify-cli\node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm64@4.1.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})

+ gify-cli@1.0.2
updated 1 package in 3.021s

C:\whatsapp-bot-master>npm i
audited 789 packages in 7.378s

57 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\whatsapp-bot-master>npmm start
'npmm' is not recognized as an internal or external command,
operable program or batch file.

C:\whatsapp-bot-master>npm start

> whatsapp-bot@2.0.0 start C:\whatsapp-bot-master
> node index.js

C:\whatsapp-bot-master\lib\help.js:135
    return `Daftar channel:
            ^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\whatsapp-bot-master\msgHndlr.js:17:58)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@2.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-13T07_29_42_396Z-debug.log

C:\whatsapp-bot-master>

**Comment by gauravsharma99** [comment]
did you start npm first or do you already have it installed?

**Comment by CE-10** [comment]
coba di cek di lib/help.js

**Comment by Limsatrya** [comment]
> coba di cek di lib/help.js

exports.snk = snk()
function donate() {
    return `Ya halo om.. Mau donate?
    
Donate donate tai ajg
}
exports.donate = donate()
function listChannel() {
    return `Daftar channel: 
1. ANTV
2. GTV
3. Indosiar
4. iNewsTV
5. KompasTV
6. MNCTV
7. METROTV
8. NETTV
9. RCTI
10. SCTV
11. RTV
12. Trans7
13. TransTV`
}
exports.listChannel = listChannel()

**Comment by Limsatrya** [comment]
ada yang salah kah dibagian "Daftar Channel" ?

**Comment by Limsatrya** [comment]
WOY BANGSSAT!
