### ISSUE TITLE
message is missing critical data needed to download the file

### ISSUE THREAD

**Issue by aymenitc** [MhankBarBar/whatsapp-bot#207]
I'm getting this error today when quoting image or gif
for example when I caption image with !sticker it works fine, but when quote a message image I get this error
```
[ERROR] Error: message is missing critical data needed to download the file.
    at /home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:83:27
    at step (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:44:23)
    at Object.next (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:25:53)
    at /home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:15:12)
    at exports.decryptMedia (/home/aymenitc/whatsapp-bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:67:71)
    at msgHandler (/home/aymenitc/whatsapp-bot/msgHndlr.js:134:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by lxndr-rl** [comment]
I think this is already fixed, update wa-automate-nodejs and wa-decrypt

**Comment by aymenitc** [comment]
I updated wa-automate an hour a go, but how about wa-decrypt? how to update it

**Comment by lxndr-rl** [comment]
npm
`npm install @open-wa/wa-decrypt@latest `
yarn
`yarn upgrade @open-wa/wa-decrypt --latest `

**Comment by aymenitc** [comment]
thank you man. it works 100%.
you always help me I appreciate it ;)

**Comment by lxndr-rl** [comment]
Your welcome. Don't forget close this issue
