### ISSUE TITLE
TypeError: client.onGlobalParicipantsChanged is not a function

### ISSUE THREAD

**Issue by Jerukpurut** [MhankBarBar/whatsapp-bot#212]
TypeError: client.onGlobalParicipantsChanged is not a function
    at start (C:\Users\*\Downloads\Compressed\whatsapp-bot-master\index.js:24:16)
    at C:\Users\*\Downloads\Compressed\whatsapp-bot-master\index.js:51:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by Jerukpurut** [comment]
nevermind dah fix

**Comment by oLittleStars** [comment]
> deixa pra lá, consertar

could you tell me how?
