### ISSUE TITLE
error while starting

### ISSUE THREAD

**Issue by ArmyNicolasG** [MhankBarBar/whatsapp-bot#213]
Error: Cannot find module '@open-wa/wa-decrypt'
Require stack:
- D:\Programacion\APIs\bots\whatsapp2\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Programacion\APIs\bots\whatsapp2\main.js:1:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\Programacion\\APIs\\bots\\whatsapp2\\main.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp2@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp2@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
that code starts

**Describe alternatives you've considered**
using another bot

**Additional context**

**Comment by aymenitc** [comment]
npm
npm install @open-wa/wa-automate@latest

yarn
yarn upgrade @open-wa/wa-automate --latest

Also you need upgrade @open-wa/wa-decrypt
