### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by Alis-Dev-idn** [MhankBarBar/whatsapp-bot#223]
✓ Authenticated
✓ WAPI Reinjected
✓ Client is ready
✓ Patches Installed: #####
✓ Client loaded in 9.861s
✓ 🚀 @OPEN-WA ready for account: ####
[SERVER] Server Started!
TypeError: client.onGlobalParicipantsChanged is not a function
    at start (/home/wabot/whatsapp-bot/index.js:24:16)
    at /home/wabot/whatsapp-bot/index.js:51:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by kios19** [comment]
same here. did you find a solution?

**Comment by hacker45tech** [comment]
Not yet

**Comment by bennyJCc** [comment]
HAVE YOU FOUND THE SOLUTION YET?

**Comment by necrosome-lab** [comment]
Same problem

**Comment by Danprogrammer1** [comment]
I had the same problem, I think this bot is no longer working. If you guys find a solution tell me!

**Comment by hacker45tech** [comment]
No solution here.anyone who knows how to us e huroku website for building a
bot

**Comment by necrosome-lab** [comment]
I figured it out, It has a typo.
It says Paricipants intead of Participants

TypeError: client.onGlobal**Paricipants**Changed is not a function
at start (/home/wabot/whatsapp-bot/index.js:24:16)
at /home/wabot/whatsapp-bot/index.js:51:21
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:93:5)

So you have to check and rewrite that wrote at those specific files.
In this case, **index.js** and apparently also **task_queues.js**

**Comment by hacker45tech** [comment]
Thanks, I'll check it out.

**Comment by kartikey15** [comment]
Did it work? Fixing the typo...
