### ISSUE TITLE
ytmp4 eror kah?

### ISSUE THREAD

**Issue by agusydk3** [MhankBarBar/whatsapp-bot#41]
![IMG_20201006_225032](https://user-images.githubusercontent.com/57493908/95225807-628b2e00-0826-11eb-862c-66fae6bf2e5e.jpg)

**Comment by MhankBarBar** [comment]
Bisa send lognya gan?

**Comment by agusydk3** [comment]
> Bisa send lognya gan?

Ini a


~> [EXEC] 06/10 22:50:15 !ytmp4 from Agus DxD
Something went wrong Error: Cannot find file. Make sure the file reference is relative or valid DataURL
    at Client.<anonymous> (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:829:35)
    at step (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:63:23)
    at Object.next (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:53)
    at /root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:34:12)
    at Client.sendImage (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:817:16)
    at Client.<anonymous> (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:893:33)
    at step (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:63:23)
    at Object.next (/root/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/api/Client.js:44:53)
![Uploading IMG_20201006_225442.jpg…]()

**Comment by MhankBarBar** [comment]
Update module wa-automate nya

**Comment by agusydk3** [comment]
> Update module wa-automate nya

Cara update nya gimana a?

**Comment by MhankBarBar** [comment]
sama loh masalahnya [kek disini](https://github.com/MhankBarBar/whatsapp-bot/issues/34)

**Comment by agusydk3** [comment]
> sama loh masalahnya [kek disini](https://github.com/MhankBarBar/whatsapp-bot/issues/34)

Oalah ga liat a
Btw Thanks yaa

**Comment by MhankBarBar** [comment]
Oke
