### ISSUE TITLE
chrome path eror

### ISSUE THREAD

**Issue by java-cyber-army** [MhankBarBar/whatsapp-bot#44]
ChromePathNotSetError
    at new LauncherError (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/utils.js:37:22)
    at new ChromePathNotSetError (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/utils.js:44:9)
    at Object.linux (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
    at Function.getInstallations (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/chrome-launcher.js:135:51)
    at /workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:260:69
    at step (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:63:23)
    at Object.next (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:44:53)
    at fulfilled (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.',
  code: 'ERR_LAUNCHER_PATH_NOT_SET'

ini kenapa ya gan

**Comment by MhankBarBar** [comment]
`message: 'The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.'`

Disitu udh jelas padahal kok nanya?

**Comment by restugbk** [comment]
wkwkwk kan cuma tau make maklum bro

> `message: 'The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.'`
> 
> Disitu udh jelas padahal kok nanya?

**Comment by Cahyo224** [comment]
> ChromePathNotSetError
> at new LauncherError (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/utils.js:37:22)
> at new ChromePathNotSetError (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/utils.js:44:9)
> at Object.linux (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
> at Function.getInstallations (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/chrome-launcher/dist/chrome-launcher.js:135:51)
> at /workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:260:69
> at step (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:63:23)
> at Object.next (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:44:53)
> at fulfilled (/workspace/NextSimpleStarter/whatsapp-bot/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:35:58)
> at processTicksAndRejections (internal/process/task_queues.js:97:5) {
> message: 'The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.',
> code: 'ERR_LAUNCHER_PATH_NOT_SET'
> 
> ini kenapa ya gan

itu kan udah di jelasin salahnya kenapa
