### ISSUE TITLE
botnya tidak  bisa

### ISSUE THREAD

**Issue by ubed354311** [MhankBarBar/whatsapp-bot#80]
SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/kali/whatsapp-bot/msgHndlr.js:16:58)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code 1
npm ERR! path /home/kali/whatsapp-bot
npm ERR! command failed
npm ERR! command sh -c node index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2020-10-25T17_49_53_751Z-debug.log

**Comment by ItzTobz** [comment]
Usahakan taruh/clone di Folder C:

Ketik
> cd C:/whatsapp-bot
> npm start (Jika sudah menginstall npm)
Atau juga bisa
> node index.js
