### ISSUE TITLE
mhank kok pas npm start ada error spawn

### ISSUE THREAD

**Issue by andra12lol** [MhankBarBar/whatsapp-bot#86]
Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (D:\Andra 2\whatsapp-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (D:\Andra 2\whatsapp-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by MhankBarBar** [comment]
??

**Comment by andra12lol** [comment]
> ??

Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (D:\Andra 2\whatsapp-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (D:\Andra 2\whatsapp-bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by MhankBarBar** [comment]
Itu dah jelas loh, kalo chromenya ga ke baca

**Comment by andra12lol** [comment]
> Itu dah jelas loh, kalo chromenya ga ke baca

jadi harus gimana mhank?

**Comment by MhankBarBar** [comment]
Path chrome lu dimana
Ex : `C:\Program\Google\Chrome\Application\chrome.exe` atau di  `C:\Program (X86)\Google\Chrome\Application\chrome.exe` ?? Atau blom diinstall?

**Comment by andra12lol** [comment]
> Path chrome lu dimana
> Ex : `C:\Program\Google\Chrome\Application\chrome.exe` atau di `C:\Program (X86)\Google\Chrome\Application\chrome.exe` ?? Atau blom diinstall?

blom di install

**Comment by MhankBarBar** [comment]
Sip ngelawak, install dulu chromenya

Close

**Comment by MFarelS** [comment]
> Sip ngelawak, install dulu chromenya
> 
> Close

Awokwaokwaokwaok Tomlolnya Alami
